name: Code Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '44 15 * * 5'

permissions:
  contents: read

jobs:
  msdo-iac:
    name: Run Azure Defender for DevOps IaC scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@08976cb623803b1b36d7112d4ff9f59eae704de0 # v1.12.0
        id: msdo
        with:
          categories: 'IaC'

      - name: Upload results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      - name: Upload alerts file as a workflow artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: alerts
          path: ${{ steps.msdo.outputs.sarifFile }}